export default {
  index: "Willkommen zur Qwen Code Dokumentation",
  deployment: "Ausführung & Bereitstellung",
  architecture: "Architektur-Übersicht",
  cli: "CLI Nutzungsanleitung",
  core: "Kern-Details",
  tools: "Tools Sammlung",
  checkpointing: "Checkpointing-Funktion",
  extension: "Erweiterungs-Entwicklung",
  "ide-integration": "IDE Integration",
  telemetry: "Observabilität",
  examples: "Beispielcode",
  npm: "Paket-Management",
  "gemini-ignore": "Ignorier-Datei Konfiguration",
  "integration-tests": "Integrationstests",
  "keyboard-shortcuts": "Tastaturkürzel",
  sandbox: "Sandbox-Mechanismus",
  "issue-and-pr-automation": "Automatisierte Behandlung",
  troubleshooting: "Fehlerbehebung",
  "tos-privacy": "Nutzungsbedingungen & Datenschutz",
  Uninstall: "Deinstallations-Anleitung",
};
