export default {
  index: "Welcome to Qwen Code Documentation",
  deployment: "Execution & Deployment",
  architecture: "Architecture Overview",
  cli: "CLI Usage Guide",
  core: "Core Details",
  tools: "Tools Collection",
  checkpointing: "Checkpointing Feature",
  extension: "Extension Development",
  "ide-integration": "IDE Integration",
  telemetry: "Observability",
  examples: "Example Code",
  npm: "Package Management",
  "gemini-ignore": "Ignore File Configuration",
  "integration-tests": "Integration Tests",
  "keyboard-shortcuts": "Keyboard Shortcuts",
  sandbox: "Sandbox Mechanism",
  "issue-and-pr-automation": "Automation Handling",
  troubleshooting: "Troubleshooting",
  "tos-privacy": "Terms of Service & Privacy",
  Uninstall: "Uninstall Guide",
};
