export default {
  index: "Bienvenue dans la Documentation Qwen Code",
  deployment: "Exécution et Déploiement",
  architecture: "Vue d'ensemble de l'Architecture",
  cli: "Guide d'Utilisation CLI",
  core: "Détails du Noyau",
  tools: "Collection d'Outils",
  checkpointing: "Fonctionnalité de Checkpointing",
  extension: "Développement d'Extensions",
  "ide-integration": "Intégration IDE",
  telemetry: "Observabilité",
  examples: "Code d'Exemple",
  npm: "Gestion des Packages",
  "gemini-ignore": "Configuration des Fichiers à Ignorer",
  "integration-tests": "Tests d'Intégration",
  "keyboard-shortcuts": "Raccourcis Clavier",
  sandbox: "Mécanisme Sandbox",
  "issue-and-pr-automation": "Traitement Automatisé",
  troubleshooting: "Dépannage",
  "tos-privacy": "Conditions d'Utilisation et Confidentialité",
  Uninstall: "Guide de Désinstallation",
};
