export default {
  index: "欢迎阅读 Qwen Code 文档",
  deployment: "执行与部署",
  architecture: "架构概述",
  cli: "CLI 使用指南",
  core: "核心详情",
  tools: "工具集合",
  checkpointing: "检查点功能",
  extension: "扩展开发",
  "ide-integration": "IDE 集成",
  telemetry: "可观测性",
  examples: "示例代码",
  npm: "包管理",
  "gemini-ignore": "忽略文件配置",
  "integration-tests": "集成测试",
  "keyboard-shortcuts": "快捷键参考",
  sandbox: "沙箱机制",
  "issue-and-pr-automation": "自动化处理",
  troubleshooting: "故障排除",
  "tos-privacy": "服务条款与隐私",
  Uninstall: "卸载指南",
};
