export default {
  index: "Qwen Code ドキュメントへようこそ",
  deployment: "実行とデプロイ",
  architecture: "アーキテクチャ概要",
  cli: "CLI 使用ガイド",
  core: "コア詳細",
  tools: "ツールコレクション",
  checkpointing: "チェックポイント機能",
  extension: "拡張開発",
  "ide-integration": "IDE 統合",
  telemetry: "可観測性",
  examples: "サンプルコード",
  npm: "パッケージ管理",
  "gemini-ignore": "無視ファイル設定",
  "integration-tests": "統合テスト",
  "keyboard-shortcuts": "キーボードショートカット",
  sandbox: "サンドボックス機構",
  "issue-and-pr-automation": "自動化処理",
  troubleshooting: "トラブルシューティング",
  "tos-privacy": "利用規約とプライバシー",
  Uninstall: "アンインストールガイド",
};
