export default {
  index: "Добро пожаловать в документацию Qwen Code",
  deployment: "Выполнение и Развертывание",
  architecture: "Обзор Архитектуры",
  cli: "Руководство по использованию CLI",
  core: "Основные Детали",
  tools: "Коллекция Инструментов",
  checkpointing: "Функция Контрольных Точек",
  extension: "Разработка Расширений",
  "ide-integration": "Интеграция с IDE",
  telemetry: "Наблюдаемость",
  examples: "Примеры Кода",
  npm: "Управление Пакетами",
  "gemini-ignore": "Конфигурация Игнорируемых Файлов",
  "integration-tests": "Интеграционные Тесты",
  "keyboard-shortcuts": "Горячие Клавиши",
  sandbox: "Механизм Песочницы",
  "issue-and-pr-automation": "Автоматизированная Обработка",
  troubleshooting: "Устранение Неполадок",
  "tos-privacy": "Условия Использования и Конфиденциальность",
  Uninstall: "Руководство по Удалению",
};
